### ISSUE TITLE
Cannot get VBO to draw?

### ISSUE THREAD

**Issue by Triangle345** [go-gl/example#22]
I'm not sure if I'm doing everything correctly here.  Some help would be greatly appreciated:

I have a window setup using glfw and I have glortho setup.  I have had luck drawing with a more "raw" open gl library.  But for some reason I cannot do it with this library.  My code is as follows(it is not full code but only opengl parts):

```
    vars:
    idxs = [...]uint32{0, 1, 2}

verts = [...]int32{10, 10, 0, 20, 20, 0, 40, 20, 0}


buf := GenBuffer()
BufferData(ARRAY_BUFFER, 9*4, verts[:], STATIC_READ)
buf.Bind(ARRAY_BUFFER)

bufel := GenBuffer()
BufferData(ELEMENT_ARRAY_BUFFER, 3*4, idxs[:], STATIC_READ)
bufel.Bind(ELEMENT_ARRAY_BUFFER)

buf.Bind(ARRAY_BUFFER)
EnableClientState(VERTEX_ARRAY)
VertexPointer(3, INT, 0, verts[:])
bufel.Bind(ELEMENT_ARRAY_BUFFER)
DrawElements(TRIANGLE_STRIP, 3, UNSIGNED_INT, idxs[:])
if GetError() != NO_ERROR {
    t.Error("slice failed")
}

DisableClientState(VERTEX_ARRAY)
```

I cannot get this to draw on my screen for some reason.  Any tips?

**Comment by whiteShtef** [comment]
bump
