### ISSUE TITLE
More information in examples

### ISSUE THREAD

**Issue by SCKelemen** [go-gl/example#64]
I'd like to try and render a particle system in gl with golang, but it's difficult to understand what is happening even with the example cube. Could you provide a simple example in working with particles, or provide a basic tutorial, or annotate the code?

**Comment by SCKelemen** [comment]
I've actually made quite a bit of progress. Is there any documentation? I'd like to know how to color vertices.

**Comment by shurcooL** [comment]
These examples are for helping understand how to use the go-gl Go packages that expose OpenGL API. They're not meant to be examples for OpenGL itself.

Your best bet is to look at more dedicated resources or community sites for OpenGL, such as https://www.opengl-tutorial.org/ (first result from Google, but try [others](https://www.google.com/search?q=opengl+tutorial). This is an issue tracker for issues with the go-gl examples.
