### ISSUE TITLE
gl21-cube: Cube in demo appears squashed.

### ISSUE THREAD

**Issue by nf** [go-gl/example#65]
The [cube](https://github.com/go-gl/example/raw/master/gl21-cube/Screenshot.png) in the demo is squashed. It looks like an aspect ratio thing. I can't see anything in the source that would cause this. Any ideas?

**Comment by nf** [comment]
After some digging the fix is kind of obvious:

```
diff --git a/gl21-cube/cube.go b/gl21-cube/cube.go
index 5a84ebc..b26b8f2 100644
--- a/gl21-cube/cube.go
+++ b/gl21-cube/cube.go
@@ -29,6 +29,8 @@ func init() {
        runtime.LockOSThread()
 }
 
+const width, height = 1280, 720
+
 func main() {
        if err := glfw.Init(); err != nil {
                log.Fatalln("failed to initialize glfw:", err)
@@ -38,7 +40,8 @@ func main() {
        glfw.WindowHint(glfw.Resizable, glfw.False)
        glfw.WindowHint(glfw.ContextVersionMajor, 2)
        glfw.WindowHint(glfw.ContextVersionMinor, 1)
-       window, err := glfw.CreateWindow(800, 600, "Cube", nil, nil)
+       monitor := glfw.GetPrimaryMonitor()
+       window, err := glfw.CreateWindow(width, height, "Cube", monitor, nil)
        if err != nil {
                panic(err)
        }
@@ -115,7 +118,9 @@ func setupScene() {
 
        gl.MatrixMode(gl.PROJECTION)
        gl.LoadIdentity()
-       gl.Frustum(-1, 1, -1, 1, 1.0, 10.0)
+       // Correct the projection for the monitor's aspect ratio.
+       f := ((float64(width) / height) - 1) / 2
+       gl.Frustum(-1-f, 1+f, -1, 1, 1.0, 10.0)
        gl.MatrixMode(gl.MODELVIEW)
        gl.LoadIdentity()
 }
```

I'm not sure that it's worth including this in the example program.

**Comment by errcw** [comment]
I'd be happy to accept a PR with a fix.

**Comment by shurcooL** [comment]
Thanks for reporting this @nf.

The window is not resizable, right? In that case, the aspect ratio can be hardcoded, no need to get the monitor (which might have a different aspect ratio). For a 800x600 window, it should be 4:3.

**Comment by nf** [comment]
@errcw I'll give it a go.

@shurcooL I get the monitor to make it full screen; that's not a critical part of this fix.

**Comment by shurcooL** [comment]
Alternatively, to keep the example simpler, we can just change the window size to be square, since that's easier to compute a projection matrix for.

Note that the `gl41core-cube` example doesn't have this problem, it calculates a perspective projection matrix accurately:

https://github.com/go-gl/example/blob/ee0644b7c5650555db3c0f4d04f9ef5716e6c6ac/gl41core-cube/cube.go#L65

**Comment by shurcooL** [comment]
For reference, the way I create a perspective projection matrix in OpenGL 2.1 projects is usually something like this, but it needs [`github.com/go-gl/mathgl/mgl64`](https://godoc.org/github.com/go-gl/mathgl/mgl64) package to be imported:

```Go
gl.MatrixMode(gl.PROJECTION)
gl.LoadIdentity()
var projectionMatrix [16]float64
perspMatrix := mgl64.Perspective(mgl64.DegToRad(45), float64(windowSize[0])/float64(windowSize[1]), 1.0, 1500.0)
for i := 0; i < 16; i++ {
	projectionMatrix[i] = float64(perspMatrix[i])
}
gl.MultMatrixd(&projectionMatrix[0])
```

(The code is from an older project, it can be cleaned up to improve style.)
