### ISSUE TITLE
Handle leak on Windows at SetSize?

### ISSUE THREAD

**Issue by hajimehoshi** [go-gl/example#68]
Just calling `SetSize` seems to cause handle leak. For example,

```diff
diff --git a/gl21-cube/cube.go b/gl21-cube/cube.go
index 5a84ebc..d7ff7a7 100644
--- a/gl21-cube/cube.go
+++ b/gl21-cube/cube.go
@@ -51,8 +51,13 @@ func main() {
        texture = newTexture("square.png")
        defer gl.DeleteTextures(1, &texture)

+       i := 0
        setupScene()
        for !window.ShouldClose() {
+               i++
+               if i % 60 == 0 {
+                       window.SetSize(800 + (i / 60), 600)
+               }
                drawScene()
                window.SwapBuffers()
                glfw.PollEvents()
```

keeps increasing the handle count on the task manager on Windows.

I tested this with glfw 3.2.

**Comment by hajimehoshi** [comment]
This also happens on glfw 3.3. I'll test glfw itself later.

**Comment by pwaller** [comment]
It would be better to file this over in https://github.com/go-gl/glfw/issues, since it is likely a GLFW issue. You're more likely to find an audience there.

**Comment by hajimehoshi** [comment]
Sure, but I'll post this to glfw/glfw when I found this is a bug in GLFW itself.

**Comment by hajimehoshi** [comment]
https://github.com/glfw/glfw/issues/1343

OK this looks like a problem in GLFW.
